# Generated by Django 6.0.3 on 2026-03-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('merchant', 'sku'), name='unique_sku_per_merchant'), models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('merchant', 'barcode'), name='unique_barcode_per_merchant')],
            },
        ),
    ]
