# Generated by Django 6.0.3 on 2026-04-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_per_merchant',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_barcode_per_merchant',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
