# Generated by Django 6.0.3 on 2026-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='invoice_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos/'),
        ),
    ]
