# Generated by Django 6.0.3 on 2026-03-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_payment_currency', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pricing_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_pricing_currency', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount_payment_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
