# Generated by Django 6.0.3 on 2026-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment_currency_payment_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount_payment_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
