# Generated by Django 6.0.3 on 2026-03-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
    ]
