# Generated by Django 6.0.3 on 2026-04-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
