# Generated by Django 6.0.3 on 2026-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_payment_original_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
