# Generated by Django 6.0.3 on 2026-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='offline_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
