# Generated by Django 6.0.3 on 2026-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_phone_per_merchant',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__gt', '')), fields=('merchant', 'phone'), name='unique_phone_per_merchant'),
        ),
    ]
